import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "rVVeLdouViU",
    video_title: "How to Build Your Perfect Resume?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "JSZmQxg3fos",
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "10:12",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "ufRtWGd0cXo",
    video_title:
      "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
    video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "ufRtWGd0cXo",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:18",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "7OuSRaIPOds",
    video_title:
      "The Real Reason You Can't Change (And How to Fix It in 21 Days) | Angela Orr",
    video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
    tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
    cover_image: "7OuSRaIPOds",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:13",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "esjJzKjx9Fo",
    video_title: "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
    video_description: `Feeling stuck, lost, or like your best years are behind you? You're not alone and you're not too late.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "esjJzKjx9Fo",
    publish_date: "2025-07-11",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:59",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "Qwwgg_qt5ew",
    video_title: "Apply logic to simplify your conditional problems",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["Coding Tips", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "Qwwgg_qt5ew",
    publish_date: "2024-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "2:44",
    software_used: ["After Effects"],
  },
  {
    id: "TiZvFO99rpw",
    video_title: "HTTP Request Explained in 1 minute",
    video_description:
      "Every time you visit a website, your browser sends an HTTP request, and the server responds. But how does this process actually work?",
    tags: ["HTTP", "Web Basics", "Networking", "Shorts"],
    cover_image: "TiZvFO99rpw",
    publish_date: "2025-02-27",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/TiZvFO99rpw?si=vUl9yE-xeKhfq8gd",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "1:10",
    software_used: ["After Effects"],
  },
  {
    id: "2esQF01ob78",
    video_title: "API & API Endpoints Explained with Simple Examples",
    video_description:
      "Every time you use an app or website, APIs are working behind the scenes to fetch data. But what exactly is an API, and how do API endpoints work? Watch this video to learn with simple examples!",
    tags: ["API", "Web Basics", "Backend", "Shorts"],
    cover_image: "2esQF01ob78",
    publish_date: "2025-03-05",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2esQF01ob78?si=SRi4j6f8LWlkHpKh",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "1:24",
    software_used: ["After Effects"],
  },
  {
    id: "fH24XyxcfOc",
    video_title: "Granola to Nutritionist - Short 01",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "fH24XyxcfOc",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/fH24XyxcfOc",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:11",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "wBrkYeMlh1U",
    video_title: "Granola to Nutritionist - Short 02",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "wBrkYeMlh1U",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/wBrkYeMlh1U",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:09",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "A7O_MV3mgsI",
    video_title: "Granola to Nutritionist - Short 03",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "A7O_MV3mgsI",
    publish_date: "2025-03-07",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/A7O_MV3mgsI",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:21",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "kpJyIq-mvtc",
    video_title: "EduNurture360 Promotion | Edu Bridge Academy",
    video_description: "Experience EduNurture360 with Edu Bridge Academy: a modern learning platform designed to make education engaging, accessible, and skill-focused.",
    tags: [
      "Education",
      "Institute Promo",
      "Bangla Voiceover",
      "Brand Awareness",
    ],
    cover_image: "kpJyIq-mvtc",
    publish_date: "2024-02-01",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
    project_images: [],
    category: ["Promo"],
    duration: "1:28",
    software_used: ["After Effects"],
  },
  {
    id: "w72TzfYIsgU",
    video_title:
      "Bangladesh's First Flexible Discount for EdTech  -  Learn Without Limits!",
    video_description: `Bangladesh's First Flexible Discount for EdTech  -  Learn Without Limits!`,
    tags: ["EdTech", "Product Launch", "Education Innovation", "Motion Promo"],
    cover_image: "w72TzfYIsgU",
    publish_date: "2025-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/w72TzfYIsgU?si=50Iu8TME6mC4iH8z",
    project_images: [],
    category: ["Promo"],
    duration: "1:29",
    software_used: ["After Effect"],
  },
  {
    id: "Y3lWN7oFkpw",
    video_title: "EcoRevolution Documentary",
    video_description:
      "A compelling documentary exploring environmental sustainability and the revolution towards eco-friendly practices in modern society.",
    tags: ["Environment", "Sustainability", "Green Revolution", "Documentary"],
    cover_image: "Y3lWN7oFkpw",
    publish_date: "2024-04-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/Y3lWN7oFkpw",
    project_images: [],
    category: ["Corporate Videos"],
    duration: "3:51",
    software_used: ["After Effects"],
  },
  {
    id: "7RHcg3bsLP4",
    video_title: "Nova Foundation – Official Documentary & Intro Video",
    video_description:
      "A cinematic documentary intro produced for Nova Foundation, designed for multi-platform distribution across social media and large-scale live events. This video was showcased on a 12-foot LED screen in front of over 350+ distinguished guests during Alpha Net’s Silver Jubilee Celebration. The project combines impactful visual storytelling, polished motion graphics, and crisp audio mixing to communicate Nova Foundation's core mission and values seamlessly.",
    tags: ["Documentary", "Alpha Net", "Nova Foundation", "Silver Jubilee"],
    cover_image: "7RHcg3bsLP4",
    publish_date: "2026-08-09",
    client_name: "Nova Foundation",
    client_image: "/Nova Logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7RHcg3bsLP4",
    project_images: [],
    category: ["Documentary"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects", "Audacity"],
  },
  {
    id: "GglZ0mqxQyA",
    video_title: "Gaza Video update last",
    video_description:
      "A documentary-style Gaza update video from Sakibul Saif, delivering a compelling final update with cinematic visuals and informative storytelling.",
    tags: ["Documentary", "Gaza", "Update", "Sakibul Saif"],
    cover_image: "GglZ0mqxQyA",
    publish_date: "2026-08-09",
    client_name: "Nova Foundation",
    client_image: "/Nova Logo.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=GglZ0mqxQyA",
    project_images: [],
    category: ["Documentary"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "MCD9uyZT8Y0",
    video_title: "Programming Basics Made Simple | Stack Learner",
    video_description: `A beginner-friendly explainer video that breaks programming basics into simple, easy-to-follow lessons for new learners.`,
    tags: [
      "Programming Basics",
      "Education",
      "Beginner Tips",
      "Explainer Video",
    ],
    cover_image: "MCD9uyZT8Y0",
    publish_date: "2024-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback:
      "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
    video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
    project_images: [],
    category: ["Explainer"],
    duration: "2:43",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "i2JZPZ-a_tc",
    video_title: "Business Email Service",
    video_description: `A concise explainer of business email services, showing how companies can set up professional email systems for reliable communication and productivity.`,
    tags: ["Business IT", "Email Setup", "IT Services", "Promo Video"],
    cover_image: "i2JZPZ-a_tc",
    publish_date: "2025-07-23",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/i2JZPZ-a_tc",
    project_images: [],
    category: ["Promo"],
    duration: "1:28",
    software_used: ["After effects"],
  },
  {
    id: "H29MJ6vLbcg",
    video_title: "Stack Learner Brand Intro",
    video_description:
      "Professional brand introduction animation for Stack Learner with modern motion graphics and smooth transitions.",
    tags: [
      "Brand Animation",
      "Logo Reveal",
      "Motion Graphics",
      "Brand Identity",
    ],
    cover_image: "H29MJ6vLbcg",
    publish_date: "2024-04-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/H29MJ6vLbcg",
    project_images: [],
    category: ["Promo"],
    duration: "0:22",
    software_used: ["After Effects"],
  },
  {
    id: "TInQK-60l2A",
    video_title: "Web & E-commerce Store Development",
    video_description: `A web and e-commerce development walkthrough that highlights modern design, responsive layouts, and conversion-focused site features for online businesses.`,
    tags: ["Web Development", "E-commerce", "Business Website", "Promo"],
    cover_image: "TInQK-60l2A",
    publish_date: "2025-07-24",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/TInQK-60l2A",
    project_images: [],
    category: ["Promo"],
    duration: "1:21",
    software_used: ["After effects"],
  },
  {
    id: "byQmrdAwFK8",
    video_title: "Digital Marketing",
    video_description: `A digital marketing explainer showcasing how to create growth-driven campaigns, optimize ads, and attract the right customers for business success.`,
    tags: [
      "Marketing Strategy",
      "Conversion Optimization",
      "Business Growth",
      "Ads",
    ],
    cover_image: "byQmrdAwFK8",
    publish_date: "2025-07-25",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/byQmrdAwFK8",
    project_images: [],
    category: ["Promo"],
    duration: "1:22",
    software_used: ["After effects"],
  },
  {
    id: "M9znCGjupcY",
    video_title: "Cyber Security",
    video_description: `A cyber security awareness video that explains protection strategies, common threats, and essential best practices to keep businesses safe online.`,
    tags: [
      "Cyber Security",
      "Protection",
      "Ads",
    ],
    cover_image: "M9znCGjupcY",
    publish_date: "2025-08-01",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/M9znCGjupcY",
    project_images: [],
    category: ["Promo"],
    duration: "1:30",
    software_used: ["After effects"],
  },
  {
    id: "ppcZHepW7ak",
    video_title:
      "The Power of Asking Better Questions | Angela ORR",
    video_description: `Do you often find yourself stuck in a situation where you're not getting the answers you need because you're not asking the right questions?`,
    tags: ["Stress Relief", "Mental Health", "Wellness"],
    cover_image: "ppcZHepW7ak",
    publish_date: "2025-08-02",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ppcZHepW7ak",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:22",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "qxt_8dWBTZI",
    video_title: "Pure Pabnaiya | Rifat Official x Adda Noyon | Pabna city Song",
    video_description: "Pure Pabnaiya | Rifat official x Adda Noyon | Bangla Rap Song | Pabna city song — project by Rifat Official with high-energy editing.",
    tags: ["Music Video", "Rifat Official", "Bangla Music"],
    cover_image: "qxt_8dWBTZI",
    publish_date: "2025-01-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=qxt_8dWBTZI",
    project_images: [],
    category: ["Music Video"],
    duration: "3:22",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_02",
    video_title: "Qurbani Song 2023 | Eid-ul-Adha Special Qurbani Song",
    video_description: "Eid-ul-Adha special music video production and post-production.",
    tags: ["Music Video", "Rifat Official", "Eid Special"],
    cover_image: "lxDBCWse8mk",
    publish_date: "2025-01-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/lxDBCWse8mk",
    project_images: [],
    category: ["Music Video"],
    duration: "2:54",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_03",
    video_title: "The World cup Song 2023  -  ICC Men's ODI World Cup 2023",
    video_description: "Cricket World Cup special theme music video project.",
    tags: ["Music Video", "Rifat Official", "Sports"],
    cover_image: "abMLfpYePAo",
    publish_date: "2024-12-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/abMLfpYePAo",
    project_images: [],
    category: ["Music Video"],
    duration: "2:48",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_04",
    video_title: "Toke Vebe Jaane Kyun Bangla Version",
    video_description: "Bangla version cover music video with cinematic editing transitions.",
    tags: ["Music Video", "Rifat Official", "Cover Song"],
    cover_image: "tmKpeqPqirQ",
    publish_date: "2024-12-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/tmKpeqPqirQ",
    project_images: [],
    category: ["Music Video"],
    duration: "3:30",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "ocgk_zOtDfo",
    video_title: "Kahani Suno 2.0 Bangla Version | কাহানি শুনো | Cover Song | Rifat...",
    video_description: "Song: Kahani Suno 2.0 (Bangla Version Cover) with lyrics and vocals by SM Sabbir Rahman, music production, and seamless visual pacing.",
    tags: ["Music Video", "Rifat Official", "Cover Song"],
    cover_image: "ocgk_zOtDfo",
    publish_date: "2024-12-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=ocgk_zOtDfo",
    project_images: [],
    category: ["Music Video"],
    duration: "2:59",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_06",
    video_title: "Pure Pabnaiya 2.0  |  Miraz Afridi  |  Adda Noyon  |  2025",
    video_description: "Part 2 of the regional hit track video formatting and dynamic pacing.",
    tags: ["Music Video", "Rifat Official", "Sequel"],
    cover_image: "TohW0YbAwBc",
    publish_date: "2025-01-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/TohW0YbAwBc",
    project_images: [],
    category: ["Music Video"],
    duration: "3:28",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_07",
    video_title: "Shorbonash 2.0 | Bangla Rap 2024",
    video_description: "Bangla Rap music video project focusing on rhythmic cuts and color grading.",
    tags: ["Music Video", "Rifat Official", "Rap"],
    cover_image: "jBbOG_OiNUk",
    publish_date: "2024-11-30",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/jBbOG_OiNUk",
    project_images: [],
    category: ["Music Video"],
    duration: "2:54",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_08",
    video_title: "Meye Tui Cheat | Rifat Official",
    video_description: "Music video project execution with structural storytelling editing.",
    tags: ["Music Video", "Rifat Official", "Bangla Music"],
    cover_image: "iAwhAdycOG4",
    publish_date: "2024-11-25",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/iAwhAdycOG4",
    project_images: [],
    category: ["Music Video"],
    duration: "2:46",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_09",
    video_title: "HSC 2023 New Bangla song  -  HSC candidate must match !",
    video_description: "Student lifestyle and thematic musical track video compilation.",
    tags: ["Music Video", "Rifat Official", "Educational"],
    cover_image: "m4tNJlwWUOg",
    publish_date: "2024-11-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/m4tNJlwWUOg",
    project_images: [],
    category: ["Music Video"],
    duration: "3:30",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_10",
    video_title: "Tui Haashi (Tor Haashi) | Rifat Official - Sohan",
    video_description: "Romantic melodic track video design and seamless narrative integration.",
    tags: ["Music Video", "Rifat Official", "Romantic"],
    cover_image: "MyOfXWX5aT4",
    publish_date: "2024-11-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/MyOfXWX5aT4",
    project_images: [],
    category: ["Music Video"],
    duration: "2:40",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_11",
    video_title: "Tui Je Kothay - New Music Video 2024",
    video_description: "Modern video design with precise audio-to-video synchronization.",
    tags: ["Music Video", "Rifat Official", "Modern"],
    cover_image: "lixde3VgPrs",
    publish_date: "2024-11-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/lixde3VgPrs",
    project_images: [],
    category: ["Music Video"],
    duration: "2:29",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_12",
    video_title: "Haire Thanda - Winter Special Track",
    video_description: "Comedy / situational seasonal track dynamic video cuts.",
    tags: ["Music Video", "Rifat Official", "Comedy"],
    cover_image: "K6o9DAqHp9k",
    publish_date: "2024-11-05",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/K6o9DAqHp9k",
    project_images: [],
    category: ["Music Video"],
    duration: "2:35",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_13",
    video_title: "Soiracar - Music video Rifat official",
    video_description: "Edgy hip-hop theme editing with pacing variations.",
    tags: ["Music Video", "Rifat Official", "Hip-hop"],
    cover_image: "6aTYMGAx9e8",
    publish_date: "2024-10-30",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/6aTYMGAx9e8",
    project_images: [],
    category: ["Music Video"],
    duration: "3:12",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_14",
    video_title: "HSC Result Song 2023 Rifat Official",
    video_description: "Theme music video compilation and frame timing adjustments.",
    tags: ["Music Video", "Rifat Official", "Educational"],
    cover_image: "9Mck7Fq9_fM",
    publish_date: "2024-10-25",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/9Mck7Fq9_fM",
    project_images: [],
    category: ["Music Video"],
    duration: "2:57",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "f8PK3mRD3Qc",
    video_title: "How to use Unified chat Full Tutorial",
    video_description: "A comprehensive step-by-step screen recording and interface tutorial demonstrating how to manage all business messaging platforms via Unified Chat.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "f8PK3mRD3Qc",
    publish_date: "2025-09-07",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/f8PK3mRD3Qc",
    project_images: [],
    category: ["Tutorial Video"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_02",
    video_title: "How to cancel VPS service",
    video_description: "Step-by-step tutorial for canceling a VPS service.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "EqCuawLVE8Q",
    publish_date: "2025-09-06",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/EqCuawLVE8Q",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_03",
    video_title: "How to reinstall Vps_ Alpha net",
    video_description: "A complete tutorial for reinstalling VPS on Alpha net.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "5iFjnh7D4Vk",
    publish_date: "2025-09-05",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/5iFjnh7D4Vk",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_04",
    video_title: "How to change password",
    video_description: "Tutorial on changing your VPS password securely.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "PNP81XDgNLs",
    publish_date: "2025-09-04",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/PNP81XDgNLs",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_05",
    video_title: "How to change password RDP VPS Alpha net",
    video_description: "Step-by-step RDP VPS password change tutorial.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "a-cIDIYsnHw",
    publish_date: "2025-09-03",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/a-cIDIYsnHw",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_06",
    video_title: "Tutorial VPs 2",
    video_description: "Video tutorial covering VPS configuration and setup.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "OQNS4LXInCs",
    publish_date: "2025-09-02",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/OQNS4LXInCs",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_07",
    video_title: "How to order VPS from Alpha net",
    video_description: "Tutorial on ordering VPS from Alpha net services.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "zgCi45MWjnk",
    publish_date: "2025-09-01",
    client_name: "Unified Chat",
    client_image: "/Unified chat.png",
    client_feedback: "",
    video_link: "https://youtu.be/zgCi45MWjnk",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_01",
    video_title: "Corporate Event Video - Launch Night",
    video_description: "Cinematic recap of a corporate launch event with dynamic cuts.",
    tags: ["Event Videos", "Corporate", "Corporate Event"],
    cover_image: "aerg4sDRvak",
    publish_date: "2025-10-01",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/aerg4sDRvak?si=Pe04skTao_Q7-O5t",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_02",
    video_title: "Corporate Event Video - Gala Highlights",
    video_description: "Highlights from a corporate gala with polished motion and audio.",
    tags: ["Event Videos", "Corporate", "Gala"],
    cover_image: "T-mw_6YWmFY",
    publish_date: "2025-10-02",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/T-mw_6YWmFY?si=8pYQg466ZIFG3HhN",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_03",
    video_title: "Corporate Event Video - Conference Recap",
    video_description: "Professional event coverage with strong branding and pacing.",
    tags: ["Event Videos", "Corporate", "Conference"],
    cover_image: "AgYLselFz4Q",
    publish_date: "2025-10-03",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/AgYLselFz4Q?si=jkFTDJrSXT-wvACu",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_04",
    video_title: "Corporate Event Video - Awards Ceremony",
    video_description: "Event highlight reel with award presentation and guest reactions.",
    tags: ["Event Videos", "Corporate", "Awards"],
    cover_image: "bsl8De_W_4c",
    publish_date: "2025-10-04",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/bsl8De_W_4c?si=cQlJ5vX_5iZm_9Uk",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_05",
    video_title: "Corporate Event Video - Business Summit",
    video_description: "Summit coverage with elegant transitions and crisp editing.",
    tags: ["Event Videos", "Corporate", "Summit"],
    cover_image: "XmVygvyf4a0",
    publish_date: "2025-10-05",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/XmVygvyf4a0?si=M2h-8ckX9wNncAnE",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_06",
    video_title: "Corporate Event Video - Team Gathering",
    video_description: "A polished recap of an internal team event with branded motion.",
    tags: ["Event Videos", "Corporate", "Team Event"],
    cover_image: "Im6Mk0LGmbI",
    publish_date: "2025-10-06",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/Im6Mk0LGmbI",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_07",
    video_title: "Corporate Event Video - Client Reception",
    video_description: "Event recap tailored for client and partner reception highlights.",
    tags: ["Event Videos", "Corporate", "Reception"],
    cover_image: "jM_ov9A6OMY",
    publish_date: "2025-10-07",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/jM_ov9A6OMY",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_08",
    video_title: "Corporate Event Video - Networking Event",
    video_description: "Networking event highlights with a cinematic storytelling approach.",
    tags: ["Event Videos", "Corporate", "Networking"],
    cover_image: "pdFY0YHpSzE",
    publish_date: "2025-10-08",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/pdFY0YHpSzE",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_09",
    video_title: "Corporate Event Video - Executive Forum",
    video_description: "Executive forum coverage with engaging visuals and pacing.",
    tags: ["Event Videos", "Corporate", "Forum"],
    cover_image: "Iu5nqvptayw",
    publish_date: "2025-10-09",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/Iu5nqvptayw",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "corporate_01",
    video_title: "Corporate Video - Brand Presentation",
    video_description: "A corporate brand presentation video with polished storytelling.",
    tags: ["Corporate Videos", "Corporate", "Brand"],
    cover_image: "gahjHSdu1ro",
    publish_date: "2025-11-01",
    client_name: "Corporate Video",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/gahjHSdu1ro?si=Ld2Fbt0nudmya10C",
    project_images: [],
    category: ["Corporate Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "corporate_02",
    video_title: "Corporate Video - Company Moment",
    video_description: "A corporate video capturing a key company moment with clean edits.",
    tags: ["Corporate Videos", "Corporate", "Company"],
    cover_image: "KqE_k4P_Z2I",
    publish_date: "2025-11-02",
    client_name: "Corporate Video",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/KqE_k4P_Z2I?si=R4kL-pZ-irpP5hCH",
    project_images: [],
    category: ["Corporate Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "R4Er8qh_EkY",
    video_title: "Books suggestion Video _ Nazmous Shakib",
    video_description: "A clean talking-head video edit featuring top book suggestions by Nazmous Shakib, optimized with smooth multi-cam cuts, audio enhancement, and pacing.",
    tags: ["Talking head", "Interview", "Headshot"],
    cover_image: "R4Er8qh_EkY",
    publish_date: "2025-12-01",
    client_name: "Nazmous Shakib",
    client_image: "/nazmous-shakib a.png",
    client_feedback: "",
    video_link: "https://youtu.be/R4Er8qh_EkY",
    project_images: [],
    category: ["Talking Head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "talking_02",
    video_title: "Talking head - Executive Talk",
    video_description: "An executive talking head video with crisp framing and narrative flow.",
    tags: ["Talking head", "Executive", "Interview"],
    cover_image: "MwF1gW7war4",
    publish_date: "2025-12-02",
    client_name: "Nazmous Shakib",
    client_image: "/nazmous-shakib a.png",
    client_feedback: "",
    video_link: "https://youtu.be/MwF1gW7war4?si=CdUQ4Eoc7kZyUGe_",
    project_images: [],
    category: ["Talking head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "talking_03",
    video_title: "Talking head - Speaker Presentation",
    video_description: "A speaking head video with clean edits and clear messaging.",
    tags: ["Talking head", "Speaker", "Presentation"],
    cover_image: "THJGv6OYQFo",
    publish_date: "2025-12-03",
    client_name: "Nazmous Shakib",
    client_image: "/nazmous-shakib a.png",
    client_feedback: "",
    video_link: "https://youtu.be/THJGv6OYQFo?si=4szKLWkuUL1rE54d",
    project_images: [],
    category: ["Talking head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "-VqfDapsFLA",
    video_title: "Haramayne Real Estate Project",
    video_description: "A premium commercial real estate video showcasing Haramayan Real Estate properties, smart city architecture investment opportunities, and project highlights.",
    tags: ["Real Estate", "Commercial", "Architecture"],
    cover_image: "-VqfDapsFLA",
    publish_date: "2026-05-24",
    client_name: "Haramayne Real Estate",
    client_image: "/Haramayne Logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/-VqfDapsFLA",
    project_images: [],
    category: ["Real Estate Video"],
    duration: "3:00",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "oofT9jztcp0",
    video_title: "sms.bd promotional video",
    video_description: "A dynamic and engaging promotional video showcasing Alpha SMS gateway services, features, and bulk messaging benefits for businesses.",
    tags: ["Promotional Video", "YouTube", "Brand", "Promo"],
    cover_image: "oofT9jztcp0",
    publish_date: "2026-05-21",
    client_name: "sms.bd",
    client_image: "/sms.bd logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/oofT9jztcp0?si=oYfFEYefh7PA_a2J",
    project_images: [],
    category: ["Promotional Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "XrEp4QmFgMw",
    video_title: "Motion Reel Showcase",
    video_description: "A dynamic motion reel featuring cinematic transitions, smooth animations, and creative visual storytelling techniques.",
    tags: ["Motion Reel", "Shorts", "Motion", "Animation"],
    cover_image: "XrEp4QmFgMw",
    publish_date: "2026-05-21",
    client_name: "Motion Reel",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/XrEp4QmFgMw",
    project_images: [],
    category: ["Motion reel"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "7ULoKOlXkgs",
    video_title: "Real Estate Edit Reel",
    video_description: "A polished real estate edit showcasing cinematic pacing, elegant camera movements, and refined color grading to highlight architectural details and lifestyle. Perfect for property showcases, this reel focuses on premium storytelling, crisp motion graphics, and cinematic mood to elevate listings and brand presentation.",
    tags: ["Motion Reel", "Shorts", "Motion", "Animation"],
    cover_image: "7ULoKOlXkgs",
    publish_date: "2026-07-26",
    client_name: "Motion Reel",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/7ULoKOlXkgs?feature=share",
    project_images: [],
    category: ["Motion reel"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "motion_04",
    video_title: "Nike Product Animation 3D",
    video_description: "A concept 3D product animation exploring dynamic motion design and cinematic rendering for Nike products. Created as a personal concept project to showcase 3D motion graphics, pacing, and visual storytelling.",
    tags: ["Product Animation", "3D Animation", "Nike"],
    cover_image: "J_d-QgzLlpc",
    publish_date: "2026-08-15",
    client_name: "Nike",
    client_image: "/companies/Nike-Logo.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/J_d-QgzLlpc",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["Adobe After Effects", "Adobe Premiere Pro"],
    timelineImage: "/Nike-project.png",
  },
  {
    id: "n5m67OJfXsk",
    video_title: "Silver Jubilee Logo animation_ Alpha Net",
    video_description: "Logo animation for Silver Jubilee Alpha Net project.",
    tags: ["Logo animation", "Motion Graphics"],
    cover_image: "n5m67OJfXsk",
    publish_date: "2026-06-22",
    client_name: "Alpha Net",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/n5m67OJfXsk",
    project_images: [],
    category: ["Logo animation"],
    duration: "",
    software_used: ["Adobe After Effects"],
  },
  {
    id: "qDxNK0sQZzs",
    video_title: "Logo Intro Rifat Official ( Music Video )",
    video_description: "Logo animation for Rifat Official, created as a cinematic intro.",
    tags: ["Logo animation", "Motion Graphics"],
    cover_image: "qDxNK0sQZzs",
    publish_date: "2026-06-22",
    client_name: "Rifat Official",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/qDxNK0sQZzs",
    project_images: [],
    category: ["Logo animation"],
    duration: "",
    software_used: ["After Effects"],
  },
  {
    id: "k6qitLVyKOU",
    video_title: "Cinematic logo intro_ Saif Studio",
    video_description: "Cinematic logo intro animation produced for Saif Studio.",
    tags: ["Logo animation", "Motion Graphics"],
    cover_image: "k6qitLVyKOU",
    publish_date: "2026-06-22",
    client_name: "Saif Studio",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/k6qitLVyKOU",
    project_images: [],
    category: ["Logo animation"],
    duration: "",
    software_used: ["After Effects"],
  },
  {
    id: "N4IIZ7bAW9c",
    video_title: "15s Promotional Video | KoreanMartBD | UGC Style",
    video_description: "15s Demo Promotional Video Concept for KoreanMartBD, featuring modern motion graphics and commercial-style editing.",
    tags: ["Promotional Video", "Commercial", "KoreanMartBD"],
    cover_image: "N4IIZ7bAW9c",
    publish_date: "2026-06-22",
    client_name: "KoreanMartBD",
    client_image: "/Korean mart Logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/N4IIZ7bAW9c",
    project_images: [],
    category: ["Promotional Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "motion_05",
    video_title: "Gift Animation",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Giveaway"],
    cover_image: "gkd2jFYrD30",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://youtu.be/gkd2jFYrD30",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Gift ANimation project.png",
  },
  {
    id: "motion_06",
    video_title: "Welcome Animation For Event",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Event"],
    cover_image: "ChS8bpccL_o",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=ChS8bpccL_o",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Welcome-AlphaNet.png",
  },
  {
    id: "motion_07",
    video_title: "Gift Animation Side Wings",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Shorts"],
    cover_image: "t-dVklQ2Zkw",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/t-dVklQ2Zkw",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Gift ANimation project.png",
  },
  {
    id: "motion_07b",
    video_title: "Raffle Draw animation",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Raffle"],
    cover_image: "6H8qq7hUg4k",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=6H8qq7hUg4k",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Raffle draw project.png",
  },
  {
    id: "motion_08",
    video_title: "Mohseen Side Wings Animation",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Shorts"],
    cover_image: "O5d62igCEg4",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/O5d62igCEg4",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Mohseen Project.png",
  },
  {
    id: "motion_09",
    video_title: "Alora Cloud Side Wings Animation",
    video_description: "Event-specific motion graphics created for **Alpha Net's Silver Jubilee celebration**, designed to run as **continuous loops on the Main LED and Side Wing LED screens** throughout the event.\n\nThe visuals were created to enhance the stage experience, maintain a consistent **25 Years / Silver Jubilee brand identity**, and provide premium animated backgrounds for different moments of the celebration.\n\n**Purpose:** Main LED & Side Wing LED Loop Visuals\n**Event:** Alpha Net Silver Jubilee\n**Software:** Adobe After Effects",
    tags: ["Animation", "Motion Graphics", "Shorts"],
    cover_image: "iQCsarSa-lQ",
    publish_date: "2026-08-15",
    client_name: "Alpha Net",
    client_image: "/companies/alpha-net.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/iQCsarSa-lQ",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["After Effects"],
    timelineImage: "/Alora Cloud Project.png",
  },
];

export const featuredVideoProjectIds = [
  "qxt_8dWBTZI",
  "ocgk_zOtDfo",
  "oofT9jztcp0",
  "uI1jJ0z97TA",
  "R4Er8qh_EkY",
  "f8PK3mRD3Qc",
  "-VqfDapsFLA",
  "N4IIZ7bAW9c",
  "6H8qq7hUg4k",
  "7RHcg3bsLP4",
  "GglZ0mqxQyA",
];

export const featuredVideoProjects: VideoProject[] = featuredVideoProjectIds
  .map((id) => allVideoProjects.find((project) => project.id === id))
  .filter((project): project is VideoProject => !!project);



