import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "rVVeLdouViU",
    video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "6:32",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "JSZmQxg3fos",
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "10:12",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "ufRtWGd0cXo",
    video_title:
      "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
    video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "ufRtWGd0cXo",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:18",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "7OuSRaIPOds",
    video_title:
      "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
    video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
    tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
    cover_image: "7OuSRaIPOds",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:13",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "esjJzKjx9Fo",
    video_title: "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
    video_description: `Feeling stuck, lost, or like your best years are behind you? You're not alone and you're not too late.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "esjJzKjx9Fo",
    publish_date: "2025-07-11",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:59",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "Qwwgg_qt5ew",
    video_title: "Apply logic to simplify your conditional problems",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["Coding Tips", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "Qwwgg_qt5ew",
    publish_date: "2024-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "2:44",
    software_used: ["After Effects"],
  },
  {
    id: "TiZvFO99rpw",
    video_title: "HTTP Request Explained in 1 minute",
    video_description:
      "Every time you visit a website, your browser sends an HTTP request, and the server responds. But how does this process actually work?",
    tags: ["HTTP", "Web Basics", "Networking", "Shorts"],
    cover_image: "TiZvFO99rpw",
    publish_date: "2025-02-27",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/TiZvFO99rpw?si=vUl9yE-xeKhfq8gd",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "1:10",
    software_used: ["After Effects"],
  },
  {
    id: "2esQF01ob78",
    video_title: "API & API Endpoints Explained with Simple Examples",
    video_description:
      "Every time you use an app or website, APIs are working behind the scenes to fetch data. But what exactly is an API, and how do API endpoints work? 🤔 Watch this video to learn with simple examples!",
    tags: ["API", "Web Basics", "Backend", "Shorts"],
    cover_image: "2esQF01ob78",
    publish_date: "2025-03-05",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2esQF01ob78?si=SRi4j6f8LWlkHpKh",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "1:24",
    software_used: ["After Effects"],
  },
  {
    id: "fH24XyxcfOc",
    video_title: "Granola to Nutritionist - Short 01",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "fH24XyxcfOc",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/fH24XyxcfOc",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:11",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "wBrkYeMlh1U",
    video_title: "Granola to Nutritionist - Short 02",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "wBrkYeMlh1U",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/wBrkYeMlh1U",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:09",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "A7O_MV3mgsI",
    video_title: "Granola to Nutritionist - Short 03",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "A7O_MV3mgsI",
    publish_date: "2025-03-07",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/A7O_MV3mgsI",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:21",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "kpJyIq-mvtc",
    video_title: "EduNurture360 কি? | Edu Bridge Academy",
    video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
    tags: [
      "Education",
      "Institute Promo",
      "Bangla Voiceover",
      "Brand Awareness",
    ],
    cover_image: "kpJyIq-mvtc",
    publish_date: "2024-02-01",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
    project_images: [],
    category: ["Promo"],
    duration: "1:28",
    software_used: ["After Effects"],
  },
  {
    id: "w72TzfYIsgU",
    video_title:
      "Bangladesh’s First Flexible Discount for EdTech – Learn Without Limits!",
    video_description: `Bangladesh's First Flexible Discount for EdTech – Learn Without Limits!`,
    tags: ["EdTech", "Product Launch", "Education Innovation", "Motion Promo"],
    cover_image: "w72TzfYIsgU",
    publish_date: "2025-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/w72TzfYIsgU?si=50Iu8TME6mC4iH8z",
    project_images: [],
    category: ["Promo"],
    duration: "1:29",
    software_used: ["After Effect"],
  },
  {
    id: "Y3lWN7oFkpw",
    video_title: "EcoRevolution Documentary",
    video_description:
      "A compelling documentary exploring environmental sustainability and the revolution towards eco-friendly practices in modern society.",
    tags: ["Environment", "Sustainability", "Green Revolution", "Documentary"],
    cover_image: "Y3lWN7oFkpw",
    publish_date: "2024-04-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/Y3lWN7oFkpw",
    project_images: [],
    category: ["Documentary"],
    duration: "3:51",
    software_used: ["After Effects"],
  },
  {
    id: "MCD9uyZT8Y0",
    video_title: "প্রোগ্রামিং এর ফান্ডামেন্টাল শেখা কেন জরুরী?",
    video_description: `ফান্ডামেন্টাল না শিখে কাজ শেখা শুরু করলে কেন সমস্যা হয়—এই ভিডিওতে জানুন।`,
    tags: [
      "Programming Basics",
      "Education",
      "Beginner Tips",
      "Explainer Video",
    ],
    cover_image: "MCD9uyZT8Y0",
    publish_date: "2024-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback:
      "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
    video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
    project_images: [],
    category: ["Explainer"],
    duration: "2:43",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "i2JZPZ-a_tc",
    video_title: "Business Email Service",
    video_description: `একটি ভুল ইমেইল কনফিগারেশনের কারণে নষ্ট হতে পারে আপনার সবচেয়ে valuable ক্লায়েন্ট ও ব্যবসার সুনাম।`,
    tags: ["Business IT", "Email Setup", "IT Services", "Promo Video"],
    cover_image: "i2JZPZ-a_tc",
    publish_date: "2025-07-23",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/i2JZPZ-a_tc",
    project_images: [],
    category: ["Promo"],
    duration: "1:28",
    software_used: ["After effects"],
  },
  {
    id: "H29MJ6vLbcg",
    video_title: "Stack Learner Brand Intro",
    video_description:
      "Professional brand introduction animation for Stack Learner with modern motion graphics and smooth transitions.",
    tags: [
      "Brand Animation",
      "Logo Reveal",
      "Motion Graphics",
      "Brand Identity",
    ],
    cover_image: "H29MJ6vLbcg",
    publish_date: "2024-04-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/H29MJ6vLbcg",
    project_images: [],
    category: ["Promo"],
    duration: "0:22",
    software_used: ["After Effects"],
  },
  {
    id: "TInQK-60l2A",
    video_title: "Web & E-commerce Store Development",
    video_description: `ওয়েবসাইট হতে হয় ফাস্ট, স্মার্ট, ও ইনটুইটিভ — যাতে বাড়ে ব্যবসার conversion.`,
    tags: ["Web Development", "E-commerce", "Business Website", "Promo"],
    cover_image: "TInQK-60l2A",
    publish_date: "2025-07-24",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/TInQK-60l2A",
    project_images: [],
    category: ["Promo"],
    duration: "1:21",
    software_used: ["After effects"],
  },
  {
    id: "byQmrdAwFK8",
    video_title: "Digital Marketing",
    video_description: `ভিজিটর আসছে, কিন্তু কাস্টমার হচ্ছে না? সমস্যা প্রোডাক্টে না, মার্কেটিং সিস্টেমে।`,
    tags: [
      "Marketing Strategy",
      "Conversion Optimization",
      "Business Growth",
      "Ads",
    ],
    cover_image: "byQmrdAwFK8",
    publish_date: "2025-07-25",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/byQmrdAwFK8",
    project_images: [],
    category: ["Promo"],
    duration: "1:22",
    software_used: ["After effects"],
  },
  {
    id: "M9znCGjupcY",
    video_title: "Cyber Security",
    video_description: `জাস্ট একটা wrong ক্লিক, অথবা unknown  লিংক… আর মুহূর্তেই আপনার বিজনেস হতে পারে সাইবার হ্যাকের এর  শিকার।`,
    tags: [
      "Cyber Security",
      "Protection",
      "Ads",
    ],
    cover_image: "M9znCGjupcY",
    publish_date: "2025-08-01",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/M9znCGjupcY",
    project_images: [],
    category: ["Promo"],
    duration: "1:30",
    software_used: ["After effects"],
  },
  {
    id: "ppcZHepW7ak",
    video_title:
      "The Power of Asking Better Questions | Angela ORR",
    video_description: `Do you often find yourself stuck in a situation where you're not getting the answers you need because you're not asking the right questions?`,
    tags: ["Stress Relief", "Mental Health", "Wellness"],
    cover_image: "ppcZHepW7ak",
    publish_date: "2025-08-02",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ppcZHepW7ak",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:22",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_01",
    video_title: "Pure Pabnaiya। Rifat Official x Adda Noyon। Pabna city Song",
    video_description: "Music video edited by Sakibul Saif for RIFAT OFFICIAL.",
    tags: ["Music Video", "Rifat Official", "Bangla Music"],
    cover_image: "qxt_8dWBTZI",
    publish_date: "2025-01-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/qxt_8dWBTZI",
    project_images: [],
    category: ["Music Video"],
    duration: "3:22",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_02",
    video_title: "Qurbani Song 2023 | কোরবানি ঈদের গান Qurbani Song",
    video_description: "Eid-ul-Adha special music video production and post-production.",
    tags: ["Music Video", "Rifat Official", "Eid Special"],
    cover_image: "lxDBCWse8mk",
    publish_date: "2025-01-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/lxDBCWse8mk",
    project_images: [],
    category: ["Music Video"],
    duration: "2:54",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_03",
    video_title: "The World cup Song 2023 । ICC Men's ODI World Cup 2023",
    video_description: "Cricket World Cup special theme music video project.",
    tags: ["Music Video", "Rifat Official", "Sports"],
    cover_image: "abMLfpYePAo",
    publish_date: "2024-12-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/abMLfpYePAo",
    project_images: [],
    category: ["Music Video"],
    duration: "2:48",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_04",
    video_title: "Toke vebe তোকে ভেবে। Jaane Kyun Bangla version",
    video_description: "Bangla version cover music video with cinematic editing transitions.",
    tags: ["Music Video", "Rifat Official", "Cover Song"],
    cover_image: "tmKpeqPqirQ",
    publish_date: "2024-12-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/tmKpeqPqirQ",
    project_images: [],
    category: ["Music Video"],
    duration: "3:30",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_05",
    video_title: "Kahani Suno 2.0 Bangla Version। কাহানি শুন। Cover Song",
    video_description: "Sad romantic cover song editing workflow.",
    tags: ["Music Video", "Rifat Official", "Cover Song"],
    cover_image: "ocgk_zOtDfo",
    publish_date: "2024-12-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ocgk_zOtDfo",
    project_images: [],
    category: ["Music Video"],
    duration: "2:59",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_06",
    video_title: "Pure Pabnaiya 2.0 ৷ Miraz Afridi ৷ Adda Noyon ৷ 2025",
    video_description: "Part 2 of the regional hit track video formatting and dynamic pacing.",
    tags: ["Music Video", "Rifat Official", "Sequel"],
    cover_image: "TohW0YbAwBc",
    publish_date: "2025-01-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/TohW0YbAwBc",
    project_images: [],
    category: ["Music Video"],
    duration: "3:28",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_07",
    video_title: "Shorbonash 2.0 সর্বনাশ 2.0 | Bangla Rap 2024",
    video_description: "Bangla Rap music video project focusing on rhythmic cuts and color grading.",
    tags: ["Music Video", "Rifat Official", "Rap"],
    cover_image: "jBbOG_OiNUk",
    publish_date: "2024-11-30",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/jBbOG_OiNUk",
    project_images: [],
    category: ["Music Video"],
    duration: "2:54",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_08",
    video_title: "মেয়ে তুই চিট (Meye tui cheat) Rifat Official",
    video_description: "Music video project execution with structural storytelling editing.",
    tags: ["Music Video", "Rifat Official", "Bangla Music"],
    cover_image: "iAwhAdycOG4",
    publish_date: "2024-11-25",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/iAwhAdycOG4",
    project_images: [],
    category: ["Music Video"],
    duration: "2:46",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_09",
    video_title: "HSC 2023 New Bangla song । HSC candidate must match !",
    video_description: "Student lifestyle and thematic musical track video compilation.",
    tags: ["Music Video", "Rifat Official", "Educational"],
    cover_image: "m4tNJlwWUOg",
    publish_date: "2024-11-20",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/m4tNJlwWUOg",
    project_images: [],
    category: ["Music Video"],
    duration: "3:30",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_10",
    video_title: "তোর হাঁসি (Tor Haashi) Rifat Official। Sohan",
    video_description: "Romantic melodic track video design and seamless narrative integration.",
    tags: ["Music Video", "Rifat Official", "Romantic"],
    cover_image: "MyOfXWX5aT4",
    publish_date: "2024-11-15",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/MyOfXWX5aT4",
    project_images: [],
    category: ["Music Video"],
    duration: "2:40",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_11",
    video_title: "তুই যে কোথায় । Tui je kothay । New Music Video 2024",
    video_description: "Modern video design with precise audio-to-video synchronization.",
    tags: ["Music Video", "Rifat Official", "Modern"],
    cover_image: "lixde3VgPrs",
    publish_date: "2024-11-10",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/lixde3VgPrs",
    project_images: [],
    category: ["Music Video"],
    duration: "2:29",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_12",
    video_title: "Haire Thanda । হাইরে ঠান্ডা । Winter Special Track",
    video_description: "Comedy / situational seasonal track dynamic video cuts.",
    tags: ["Music Video", "Rifat Official", "Comedy"],
    cover_image: "K6o9DAqHp9k",
    publish_date: "2024-11-05",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/K6o9DAqHp9k",
    project_images: [],
    category: ["Music Video"],
    duration: "2:35",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_13",
    video_title: "Soiracar - Music video Rifat official",
    video_description: "Edgy hip-hop theme editing with pacing variations.",
    tags: ["Music Video", "Rifat Official", "Hip-hop"],
    cover_image: "6aTYMGAx9e8",
    publish_date: "2024-10-30",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/6aTYMGAx9e8",
    project_images: [],
    category: ["Music Video"],
    duration: "3:12",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "mv_14",
    video_title: "HSC Result Song 2023 Rifat Official",
    video_description: "Theme music video compilation and frame timing adjustments.",
    tags: ["Music Video", "Rifat Official", "Educational"],
    cover_image: "9Mck7Fq9_fM",
    publish_date: "2024-10-25",
    client_name: "RIFAT OFFICIAL",
    client_image: "/companies/rifat-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/9Mck7Fq9_fM",
    project_images: [],
    category: ["Music Video"],
    duration: "2:57",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_01",
    video_title: "Unified Chat",
    video_description: "Tutorial on unified chat setup and VPS service integration.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "f8PK3mRD3Qc",
    publish_date: "2025-09-07",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/f8PK3mRD3Qc",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_02",
    video_title: "How to cancel VPS service",
    video_description: "Step-by-step tutorial for canceling a VPS service.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "EqCuawLVE8Q",
    publish_date: "2025-09-06",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/EqCuawLVE8Q",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_03",
    video_title: "How to reinstall Vps_ Alpha net",
    video_description: "A complete tutorial for reinstalling VPS on Alpha net.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "5iFjnh7D4Vk",
    publish_date: "2025-09-05",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/5iFjnh7D4Vk",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_04",
    video_title: "How to change password",
    video_description: "Tutorial on changing your VPS password securely.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "PNP81XDgNLs",
    publish_date: "2025-09-04",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/PNP81XDgNLs",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_05",
    video_title: "How to change password RDP VPS Alpha net",
    video_description: "Step-by-step RDP VPS password change tutorial.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "a-cIDIYsnHw",
    publish_date: "2025-09-03",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/a-cIDIYsnHw",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_06",
    video_title: "Tutorial VPs 2",
    video_description: "Video tutorial covering VPS configuration and setup.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "OQNS4LXInCs",
    publish_date: "2025-09-02",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/OQNS4LXInCs",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "tutorial_07",
    video_title: "How to order VPS from Alpha net",
    video_description: "Tutorial on ordering VPS from Alpha net services.",
    tags: ["Tutorial", "VPS", "Alpha net"],
    cover_image: "zgCi45MWjnk",
    publish_date: "2025-09-01",
    client_name: "Alpha Net Tutorial",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/zgCi45MWjnk",
    project_images: [],
    category: ["Tutorial"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_01",
    video_title: "Corporate Event Video - Launch Night",
    video_description: "Cinematic recap of a corporate launch event with dynamic cuts.",
    tags: ["Event Videos", "Corporate", "Corporate Event"],
    cover_image: "aerg4sDRvak",
    publish_date: "2025-10-01",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/aerg4sDRvak?si=Pe04skTao_Q7-O5t",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_02",
    video_title: "Corporate Event Video - Gala Highlights",
    video_description: "Highlights from a corporate gala with polished motion and audio.",
    tags: ["Event Videos", "Corporate", "Gala"],
    cover_image: "T-mw_6YWmFY",
    publish_date: "2025-10-02",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/T-mw_6YWmFY?si=8pYQg466ZIFG3HhN",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_03",
    video_title: "Corporate Event Video - Conference Recap",
    video_description: "Professional event coverage with strong branding and pacing.",
    tags: ["Event Videos", "Corporate", "Conference"],
    cover_image: "AgYLselFz4Q",
    publish_date: "2025-10-03",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/AgYLselFz4Q?si=jkFTDJrSXT-wvACu",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_04",
    video_title: "Corporate Event Video - Awards Ceremony",
    video_description: "Event highlight reel with award presentation and guest reactions.",
    tags: ["Event Videos", "Corporate", "Awards"],
    cover_image: "bsl8De_W_4c",
    publish_date: "2025-10-04",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/bsl8De_W_4c?si=cQlJ5vX_5iZm_9Uk",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_05",
    video_title: "Corporate Event Video - Business Summit",
    video_description: "Summit coverage with elegant transitions and crisp editing.",
    tags: ["Event Videos", "Corporate", "Summit"],
    cover_image: "XmVygvyf4a0",
    publish_date: "2025-10-05",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/XmVygvyf4a0?si=M2h-8ckX9wNncAnE",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_06",
    video_title: "Corporate Event Video - Team Gathering",
    video_description: "A polished recap of an internal team event with branded motion.",
    tags: ["Event Videos", "Corporate", "Team Event"],
    cover_image: "Im6Mk0LGmbI",
    publish_date: "2025-10-06",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/Im6Mk0LGmbI",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_07",
    video_title: "Corporate Event Video - Client Reception",
    video_description: "Event recap tailored for client and partner reception highlights.",
    tags: ["Event Videos", "Corporate", "Reception"],
    cover_image: "jM_ov9A6OMY",
    publish_date: "2025-10-07",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/jM_ov9A6OMY",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_08",
    video_title: "Corporate Event Video - Networking Event",
    video_description: "Networking event highlights with a cinematic storytelling approach.",
    tags: ["Event Videos", "Corporate", "Networking"],
    cover_image: "pdFY0YHpSzE",
    publish_date: "2025-10-08",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/pdFY0YHpSzE",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "event_09",
    video_title: "Corporate Event Video - Executive Forum",
    video_description: "Executive forum coverage with engaging visuals and pacing.",
    tags: ["Event Videos", "Corporate", "Forum"],
    cover_image: "Iu5nqvptayw",
    publish_date: "2025-10-09",
    client_name: "Corporate Event",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/Iu5nqvptayw",
    project_images: [],
    category: ["Event Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "corporate_01",
    video_title: "Corporate Video - Brand Presentation",
    video_description: "A corporate brand presentation video with polished storytelling.",
    tags: ["Corporate Videos", "Corporate", "Brand"],
    cover_image: "gahjHSdu1ro",
    publish_date: "2025-11-01",
    client_name: "Corporate Video",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/gahjHSdu1ro?si=Ld2Fbt0nudmya10C",
    project_images: [],
    category: ["Corporate Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "corporate_02",
    video_title: "Corporate Video - Company Moment",
    video_description: "A corporate video capturing a key company moment with clean edits.",
    tags: ["Corporate Videos", "Corporate", "Company"],
    cover_image: "KqE_k4P_Z2I",
    publish_date: "2025-11-02",
    client_name: "Corporate Video",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/KqE_k4P_Z2I?si=R4kL-pZ-irpP5hCH",
    project_images: [],
    category: ["Corporate Videos"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "talking_01",
    video_title: "Talking head - Insight Session",
    video_description: "A polished talking head video focusing on expert insights.",
    tags: ["Talking head", "Interview", "Headshot"],
    cover_image: "R4Er8qh_EkY",
    publish_date: "2025-12-01",
    client_name: "Talking head",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/R4Er8qh_EkY?si=0H7Ex7chN22N_ktO",
    project_images: [],
    category: ["Talking head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "talking_02",
    video_title: "Talking head - Executive Talk",
    video_description: "An executive talking head video with crisp framing and narrative flow.",
    tags: ["Talking head", "Executive", "Interview"],
    cover_image: "MwF1gW7war4",
    publish_date: "2025-12-02",
    client_name: "Talking head",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/MwF1gW7war4?si=CdUQ4Eoc7kZyUGe_",
    project_images: [],
    category: ["Talking head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "talking_03",
    video_title: "Talking head - Speaker Presentation",
    video_description: "A speaking head video with clean edits and clear messaging.",
    tags: ["Talking head", "Speaker", "Presentation"],
    cover_image: "THJGv6OYQFo",
    publish_date: "2025-12-03",
    client_name: "Talking head",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/THJGv6OYQFo?si=4szKLWkuUL1rE54d",
    project_images: [],
    category: ["Talking head"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "motion_01",
    video_title: "Moonlight full Video   Qurbani",
    video_description: "Motion graphics piece for Moonlight Qurbani campaign.",
    tags: ["Motion Graphics", "Promo"],
    cover_image: "d3fd36SYzko",
    publish_date: "2026-01-10",
    client_name: "Motion Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/d3fd36SYzko?si=VvfWCQ-4D6Nhr2yw",
    project_images: [],
    category: ["Motion Graphics"],
    software_used: ["After Effects"],
  },
  {
    id: "motion_02",
    video_title: "Zakat Project Overview | Nova Foundation",
    video_description: "Motion graphics overview for the Nova Foundation Zakat project.",
    tags: ["Motion Graphics", "Nonprofit"],
    cover_image: "nt0HHmqVsyA",
    publish_date: "2026-01-11",
    client_name: "Motion Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/nt0HHmqVsyA?si=tqC8UmqA6fPfbQ09",
    project_images: [],
    category: ["Motion Graphics"],
    software_used: ["After Effects"],
  },
  {
    id: "motion_03",
    video_title: "Eid ul adha Video Nova foundation",
    video_description: "Motion graphics short for Eid ul adha campaign.",
    tags: ["Motion Graphics", "Festival"],
    cover_image: "pvrs3Xpaarw",
    publish_date: "2026-01-12",
    client_name: "Motion Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/pvrs3Xpaarw?si=KSn3-Ns_yipzOXSM",
    project_images: [],
    category: ["Motion Graphics"],
    software_used: ["After Effects"],
  },
  {
    id: "JXVQ4NZNiCg",
    video_title: "3 Hidden AOT Secrets You Definitely Missed! (Mind = Blown)",
    video_description: "Three hidden Attack on Titan secrets you missed.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "JXVQ4NZNiCg",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/JXVQ4NZNiCg",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "u9DGTRTYbpU",
    video_title: "Revenge or Destiny? Why Grisha Chose Eren",
    video_description: "Why Grisha chose Eren — revenge or destiny?",
    tags: ["Reel", "Anime Fact"],
    cover_image: "u9DGTRTYbpU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/u9DGTRTYbpU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "k_8hPmr9KPw",
    video_title: "Why the Beard Titan Didn’t Get Eren’s Power! (Attack on Titan Explained)",
    video_description: "Why the Beard Titan didn’t inherit Eren’s power.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "k_8hPmr9KPw",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/k_8hPmr9KPw",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "rBpsvf_dkAY",
    video_title: "Eren’s Voice Actor Pushed Himself TOO FAR!",
    video_description: "Eren’s voice actor pushed himself during recording.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "rBpsvf_dkAY",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/rBpsvf_dkAY",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "HDHszbLUrc4",
    video_title: "Eren Yeager: The True Definition of Freedom!",
    video_description: "Eren Yeager’s definition of freedom explored.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "HDHszbLUrc4",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/HDHszbLUrc4",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "T_PuY0QFDSs",
    video_title: "The Vertical Manoeuvring Equipment (ODM Gear)",
    video_description: "Overview of ODM Gear used in Attack on Titan.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "T_PuY0QFDSs",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/T_PuY0QFDSs",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "NCZ5ac_zB68",
    video_title: "Who Created the Gates in Solo Leveling? | Dark Origins Revealed",
    video_description: "Origins of the Gates in Solo Leveling revealed.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "NCZ5ac_zB68",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/NCZ5ac_zB68",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "M1h_F52yLTs",
    video_title: "The Hidden Truth Behind Ymir’s Death | Attack on Titan Explained",
    video_description: "The Hidden Truth Behind Ymir’s Death",
    tags: ["Reel", "Anime Fact"],
    cover_image: "M1h_F52yLTs",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/M1h_F52yLTs",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "3fnFyVXMNJw",
    video_title: "🔍 Did Mikasa Marry Jean After Eren’s Death? The Truth Revealed! 🔔 | Attack on Titan Explained",
    video_description: "Did Mikasa Marry Jean After Eren’s Death? The Truth Revealed!",
    tags: ["Reel", "Anime Fact"],
    cover_image: "3fnFyVXMNJw",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/3fnFyVXMNJw",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "4PDdBdnVOlc",
    video_title: "Mikasa’s tears at Eren’s grave had a DEEPER meaning… and it’s heartbreaking.",
    video_description: "Mikasa’s tears at Eren’s grave had a deeper meaning.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "4PDdBdnVOlc",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/4PDdBdnVOlc",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "pTyvZOx5JJo",
    video_title: "Eren’s Incomplete Transformation EXPLAINED! (You Missed This!)",
    video_description: "Eren’s Incomplete Transformation explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "pTyvZOx5JJo",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/pTyvZOx5JJo",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "OvaI1wwER9s",
    video_title: "Eren’s Shocking Betrayal of Zeke Explained! | Attack on Titan Final Season",
    video_description: "Eren’s shocking betrayal of Zeke explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "OvaI1wwER9s",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/OvaI1wwER9s",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "d5d91FSv8FI",
    video_title: "Eren Wasn’t Supposed to Be the Main Character?!",
    video_description: "Eren wasn’t supposed to be the main character.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "d5d91FSv8FI",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/d5d91FSv8FI",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "lQqgAzQf7ow",
    video_title: "Anime Deleted THIS Scene from Attack on Titan?!",
    video_description: "Deleted scene from Attack on Titan explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "lQqgAzQf7ow",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/lQqgAzQf7ow",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "misFHNdYGFc",
    video_title: "Why Eren Couldn’t Use the Founding Titan Against the Smiling Titan!",
    video_description: "Why Eren couldn’t use the Founding Titan explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "misFHNdYGFc",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/misFHNdYGFc",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "okDZWx6J4_I",
    video_title: "The Moment Eren Knew EVERYTHING… (You Missed This!)",
    video_description: "The moment Eren knew everything explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "okDZWx6J4_I",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/okDZWx6J4_I",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "w7xQoKEboPY",
    video_title: "The Beast Titan’s Secret Power? BASEBALL.",
    video_description: "The Beast Titan’s secret power explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "w7xQoKEboPY",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/w7xQoKEboPY",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "ssqsPpi1VBw",
    video_title: "Why the Attack Titan Isn’t Invincible!",
    video_description: "Why the Attack Titan isn’t invincible.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "ssqsPpi1VBw",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/ssqsPpi1VBw",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "nwu_gXWPAeU",
    video_title: "The Drunk Guy Who Accidentally Inspired Titan – True Story!",
    video_description: "True story behind inspiration for Titans.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "nwu_gXWPAeU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/nwu_gXWPAeU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "L1Ozw10tKfY",
    video_title: "Eren Yeager’s Family Secret Will BLOW Your Mind | Attack on Titan Time Loop Explained!",
    video_description: "Eren Yeager’s family secret and time loop explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "L1Ozw10tKfY",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/L1Ozw10tKfY",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "jgZc-b0oQSg",
    video_title: "Eren’s ENTIRE Story Happened in 4 YEARS?!",
    video_description: "Eren’s entire story condensed timeline explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "jgZc-b0oQSg",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/jgZc-b0oQSg",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "inlrhASbyQI",
    video_title: "The Colossal Titan’s SHOCKING Weakness No One Saw Coming!",
    video_description: "The Colossal Titan’s surprising weakness explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "inlrhASbyQI",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/inlrhASbyQI",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "RPqm5GPCK5U",
    video_title: "Is the Marliyan Guard Talking to Us?",
    video_description: "Is the Marliyan Guard communicating hidden messages?",
    tags: ["Reel", "Anime Fact"],
    cover_image: "RPqm5GPCK5U",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/RPqm5GPCK5U",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "QSscbBr2yUc",
    video_title: "Armored Titan: The Unstoppable Force with a Hidden Weakness!",
    video_description: "Armored Titan’s hidden weakness explored.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "QSscbBr2yUc",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/QSscbBr2yUc",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "I6R5yFzPbug",
    video_title: "Attack on Titan’s Colossal Titan Secret: The Shocking Truth Behind the 60-Meter Monster!",
    video_description: "Colossal Titan secrets and origins explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "I6R5yFzPbug",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/I6R5yFzPbug",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "bm1aVc6-XMM",
    video_title: "Unleashing the Jaw Titan: Secrets You Never Knew!",
    video_description: "Jaw Titan secrets revealed.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "bm1aVc6-XMM",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/bm1aVc6-XMM",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "n4lU2uu3YXM",
    video_title: "Why Marley Waited 100 Years to Attack Paradis | AOT’s Biggest Mistake",
    video_description: "Why Marley waited 100 years to attack Paradis explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "n4lU2uu3YXM",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/n4lU2uu3YXM",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "JXVQ4NZNiCg",
    video_title: "3 Hidden AOT Secrets You Definitely Missed! (Mind = Blown)",
    video_description: "Three hidden Attack on Titan secrets you missed.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "JXVQ4NZNiCg",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/JXVQ4NZNiCg",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "u9DGTRTYbpU",
    video_title: "Revenge or Destiny? Why Grisha Chose Eren",
    video_description: "Why Grisha chose Eren — revenge or destiny?",
    tags: ["Reel", "Anime Fact"],
    cover_image: "u9DGTRTYbpU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/u9DGTRTYbpU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "k_8hPmr9KPw",
    video_title: "Why the Beard Titan Didn’t Get Eren’s Power! (Attack on Titan Explained)",
    video_description: "Why the Beard Titan didn’t inherit Eren’s power.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "k_8hPmr9KPw",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/k_8hPmr9KPw",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "rBpsvf_dkAY",
    video_title: "Eren’s Voice Actor Pushed Himself TOO FAR!",
    video_description: "Eren’s voice actor pushed himself during recording.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "rBpsvf_dkAY",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/rBpsvf_dkAY",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "HDHszbLUrc4",
    video_title: "Eren Yeager: The True Definition of Freedom!",
    video_description: "Eren Yeager’s definition of freedom explored.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "HDHszbLUrc4",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/HDHszbLUrc4",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "T_PuY0QFDSs",
    video_title: "The Vertical Manoeuvring Equipment (ODM Gear)",
    video_description: "Overview of ODM Gear used in Attack on Titan.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "T_PuY0QFDSs",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/T_PuY0QFDSs",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "NCZ5ac_zB68",
    video_title: "Who Created the Gates in Solo Leveling? | Dark Origins Revealed",
    video_description: "Origins of the Gates in Solo Leveling revealed.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "NCZ5ac_zB68",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/NCZ5ac_zB68",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "vyVu34_LTkU",
    video_title: "The Ackerman Bloodline: Why Are They SO Powerful?",
    video_description: "Why the Ackermans are so powerful explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "vyVu34_LTkU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/vyVu34_LTkU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "GXt_USewmvs",
    video_title: "Levi vs Mikasa: The Ultimate Showdown – Who Would Really Win?",
    video_description: "Levi vs Mikasa breakdown and who would win.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "GXt_USewmvs",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/GXt_USewmvs",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "SWBDRkI1FXo",
    video_title: "Eren vs. Zeke: The Ultimate Titan Showdown!",
    video_description: "Eren vs Zeke titan showdown highlights.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "SWBDRkI1FXo",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/SWBDRkI1FXo",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "NAVS-HXV0-I",
    video_title: "Jinwoo’s STRONGEST Shadow Isn’t Igris or Beru…",
    video_description: "Jinwoo’s strongest shadow explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "NAVS-HXV0-I",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/NAVS-HXV0-I",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "HUrm7e_Bom0",
    video_title: "🔥 Mikasa’s Scarf: The Hidden Meaning You MISSED! ❄️",
    video_description: "Mikasa’s scarf hidden meaning explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "HUrm7e_Bom0",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/HUrm7e_Bom0",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "m6HPtwYC0bU",
    video_title: "The REAL Enemy in Attack on Titan Will Shock You",
    video_description: "The real enemy in Attack on Titan explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "m6HPtwYC0bU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/m6HPtwYC0bU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "nlqYpt7Wbl8",
    video_title: "AOT Ending Explained! Dog titan? Did Ymir Summon Titans from the FUTURE?!",
    video_description: "AOT ending theories and Ymir explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "nlqYpt7Wbl8",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/nlqYpt7Wbl8",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "02BWmps3Ttg",
    video_title: "Fast track career growth at BIM",
    video_description: "Seminar covering career growth strategies at BIM.",
    tags: ["Seminar", "Career"],
    cover_image: "02BWmps3Ttg",
    publish_date: "2026-05-19",
    client_name: "Seminar",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/02BWmps3Ttg?si=zPBluw8TWJ95ci7j",
    project_images: [],
    category: ["Seminar Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "xpKTBc5iAuA",
    video_title: "NUB career seminar 2026",
    video_description: "Career seminar session held at NUB.",
    tags: ["Seminar", "Career"],
    cover_image: "xpKTBc5iAuA",
    publish_date: "2026-05-19",
    client_name: "Seminar",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/xpKTBc5iAuA?si=MI_nIY3awAVfGIz8",
    project_images: [],
    category: ["Seminar Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "7gh4O3tXlBs",
    video_title: "Career development program Rajshahi polytechnic institute",
    video_description: "Seminar covering career development at Rajshahi Polytechnic Institute.",
    tags: ["Seminar", "Career"],
    cover_image: "7gh4O3tXlBs",
    publish_date: "2026-05-19",
    client_name: "Seminar",
    client_image: "",
    client_feedback: "",
    video_link: "https://youtu.be/7gh4O3tXlBs",
    project_images: [],
    category: ["Seminar Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "7X_GU1pU42E",
    video_title: "Varendra university Career seminar 1",
    video_description: "Varendra University career seminar recording.",
    tags: ["Seminar", "Career"],
    cover_image: "7X_GU1pU42E",
    publish_date: "2026-05-19",
    client_name: "Seminar",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=7X_GU1pU42E",
    project_images: [],
    category: ["Seminar Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "vyVu34_LTkU",
    video_title: "The Ackerman Bloodline: Why Are They SO Powerful?",
    video_description: "Why the Ackermans are so powerful explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "vyVu34_LTkU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/vyVu34_LTkU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "GXt_USewmvs",
    video_title: "Levi vs Mikasa: The Ultimate Showdown – Who Would Really Win?",
    video_description: "Levi vs Mikasa breakdown and who would win.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "GXt_USewmvs",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/GXt_USewmvs",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "SWBDRkI1FXo",
    video_title: "Eren vs. Zeke: The Ultimate Titan Showdown!",
    video_description: "Eren vs Zeke titan showdown highlights.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "SWBDRkI1FXo",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/SWBDRkI1FXo",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "NAVS-HXV0-I",
    video_title: "Jinwoo’s STRONGEST Shadow Isn’t Igris or Beru…",
    video_description: "Jinwoo’s strongest shadow explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "NAVS-HXV0-I",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/NAVS-HXV0-I",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "HUrm7e_Bom0",
    video_title: "Mikasa’s Scarf: The Hidden Meaning You MISSED!",
    video_description: "Mikasa’s scarf hidden meaning explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "HUrm7e_Bom0",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/HUrm7e_Bom0",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "m6HPtwYC0bU",
    video_title: "The REAL Enemy in Attack on Titan Will Shock You",
    video_description: "The real enemy in Attack on Titan explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "m6HPtwYC0bU",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/m6HPtwYC0bU",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "nlqYpt7Wbl8",
    video_title: "AOT Ending Explained! Dog titan? Did Ymir Summon Titans from the FUTURE?!",
    video_description: "AOT ending theories and Ymir explained.",
    tags: ["Reel", "Anime Fact"],
    cover_image: "nlqYpt7Wbl8",
    publish_date: "2026-05-19",
    client_name: "AOT_facts",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/nlqYpt7Wbl8",
    project_images: [],
    category: ["Anime fact Reel Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "oofT9jztcp0",
    video_title: "Promotional Video",
    video_description: "A promotional video showcase for brand awareness and audience impact.",
    tags: ["Promotional Video", "YouTube", "Brand", "Promo"],
    cover_image: "oofT9jztcp0",
    publish_date: "2026-05-21",
    client_name: "Promotional Video",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=oofT9jztcp0",
    project_images: [],
    category: ["Promotional Video"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "XrEp4QmFgMw",
    video_title: "Motion Reel Showcase",
    video_description: "A dynamic motion reel featuring cinematic transitions, smooth animations, and creative visual storytelling techniques.",
    tags: ["Motion Reel", "Shorts", "Motion", "Animation"],
    cover_image: "XrEp4QmFgMw",
    publish_date: "2026-05-21",
    client_name: "Motion Reel",
    client_image: "",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/XrEp4QmFgMw",
    project_images: [],
    category: ["Motion reel"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
];



